72
73
fallen
fallen
133
134
135
136
Traceback (most recent call last):
  File "/home/yuri/Downloads/skate/venv/lib/python3.5/site-packages/cvxopt-1.2.0-py3.5-linux-x86_64.egg/cvxopt/misc.py", line 1429, in factor
    lapack.potrf(F['S']) 
ArithmeticError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuri/Downloads/skate/venv/lib/python3.5/site-packages/cvxopt-1.2.0-py3.5-linux-x86_64.egg/cvxopt/coneprog.py", line 2011, in coneqp
    matrix(0.0, (0,1)), 'beta': [], 'v': [], 'r': [], 'rti': []})
  File "/home/yuri/Downloads/skate/venv/lib/python3.5/site-packages/cvxopt-1.2.0-py3.5-linux-x86_64.egg/cvxopt/coneprog.py", line 1981, in kktsolver
    return factor(W, P)
  File "/home/yuri/Downloads/skate/venv/lib/python3.5/site-packages/cvxopt-1.2.0-py3.5-linux-x86_64.egg/cvxopt/misc.py", line 1444, in factor
    lapack.potrf(F['S']) 
ArithmeticError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuri/Downloads/skate/rl/ppo.py", line 399, in <module>
    ppo.Train()
  File "/home/yuri/Downloads/skate/rl/ppo.py", line 298, in Train
    self.GenerateTransitions()
  File "/home/yuri/Downloads/skate/rl/ppo.py", line 220, in GenerateTransitions
    self.env.Steps(actions)
  File "/home/yuri/Downloads/skate/rl/dart_env.py", line 324, in Steps
    return self.step(actions[0])
  File "/home/yuri/Downloads/skate/rl/dart_env.py", line 211, in step
    self.skel, des_accel, None, None, None, None, None, 1. / self.world.time_step())
  File "/home/yuri/Downloads/skate/PyCommon/modules/Simulator/yulQpSimulator_penalty.py", line 236, in calc_QP
    result = solvers.qp(matrix(P), matrix(q), None, None, matrix(A), matrix(b))
  File "/home/yuri/Downloads/skate/venv/lib/python3.5/site-packages/cvxopt-1.2.0-py3.5-linux-x86_64.egg/cvxopt/coneprog.py", line 4487, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "/home/yuri/Downloads/skate/venv/lib/python3.5/site-packages/cvxopt-1.2.0-py3.5-linux-x86_64.egg/cvxopt/coneprog.py", line 2013, in coneqp
    raise ValueError("Rank(A) < p or Rank([P; A; G]) < n")
ValueError: Rank(A) < p or Rank([P; A; G]) < n

Process finished with exit code 1
